services:
  vikey-inference:
    container_name: vikey-inference
    build:
      context: .
      args:
        - VIKEY_API_KEY=${VIKEY_API_KEY:-your_default_api_key_here}
        - VIKEY_API_URL=${VIKEY_API_URL:-your_default_url_key_here}
        - NODE_PORT=${NODE_PORT:-11434}
        # - EMBEDDING_API_URL=${EMBEDDING_API_URL:-https://kuzco-inference.greyscope.xyz/v1}
        # - EMBEDDING_API_KEY=${EMBEDDING_API_KEY:-your_embedding_key_here}
    ports:
      - "${NODE_PORT:-11434}:${NODE_PORT:-11434}"
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - VIKEY_API_KEY=${VIKEY_API_KEY:-your_default_api_key_here}
      - VIKEY_API_URL=${VIKEY_API_URL:-your_default_url_key_here}
      - NODE_PORT=${NODE_PORT:-11434}
      # - LLAMAEDGE_ENABLED=${LLAMAEDGE_ENABLED:-false}
      # - EMBEDDING_API_URL=${EMBEDDING_API_URL:-https://kuzco-inference.greyscope.xyz/v1}
      # - EMBEDDING_API_KEY=${EMBEDDING_API_KEY:-your_embedding_key_here}
